# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a25033fd50919cf16b9439c8b4e59206ee9057f8e3035898d1ab1b489f03d625b9594dfd606d422bb275af7fa90743c927beb1e8a54e7fa9e55eb33a18e50198

test:
  secret_key_base: 3ebcd1c7e0bd90d1d2ac6c15908d9cb682965669625d791d6bb0bd6f7ef15c0c8352d39ff1d1c9c0c2a4ea8e82c4a16c00531f382dd70e07a7607e318e216daa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
